import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import TimeDateCard from "../components/TimeDateCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: "Notes", href: "#" },
  { label: "Calendar", href: "#" },
  { label: "Books/Journal", href: "#" },
  { label: "Schedule", href: "#" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f8f9fb]`}>
        {/* Navbar */}
        <header className="w-full bg-white shadow mb-6">
          <div className="max-w-5xl mx-auto flex flex-col items-center gap-2 py-6">
            <h1 className="text-3xl font-bold tracking-wide text-[#6c63ff]">HOME PAGE</h1>
            <div className="w-full h-2 bg-gray-200 rounded mt-2 mb-2" />
          </div>
        </header>
        {/* Main Layout */}
        <div className="w-full max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-6">
          {/* Left Sidebar */}
          <aside className="md:col-span-1 flex flex-col gap-6">
            {/* Time + Date */}
            <TimeDateCard />
            {/* Navigation */}
            <div className="bg-white rounded-xl shadow p-4">
              <span className="font-semibold text-base mb-2 block">Navigation</span>
              <ul className="space-y-2">
                {navItems.map(item => (
                  <li key={item.label} className="flex items-center gap-2">
                    <input type="checkbox" className="accent-[#6c63ff]" disabled />
                    <span>{item.label}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-white rounded-xl shadow p-4 h-40 flex items-center justify-center text-gray-300">
              <span className="text-6xl">📚</span>
            </div>
          </aside>
          {/* Main Content */}
          <main className="md:col-span-3 flex flex-col gap-6">{children}</main>
        </div>
      </body>
    </html>
  );
}